### ISSUE TITLE
coshIntegral script slows down browser

### ISSUE THREAD

**Issue by axkr** [paulmasson/math#28] opened 2021-10-15 21:46 UTC
The `coshIntegral` script slows down the browser.
Is there some wrong call to coshIntegral?

```html
<html>
<head>
<meta charset="utf-8">
<title>JSXGraph</title>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/jsxgraph@1.3.2/distrib/jsxgraph.css"/>
<script src="https://cdn.jsdelivr.net/gh/paulmasson/math@1.4.6/build/math.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jsxgraph@1.3.2/distrib/jsxgraphcore.js"></script>

</head>
<body>
<div id="jxgbox" class="jxgbox"></div>
<script>
var board = JXG.JSXGraph.initBoard('jxgbox', {axis:true,boundingbox:[-2.75,6.05,2.75,-6.05]});
board.suspendUpdate();
var a = board.create('slider',[[-2.2,4.84],[2.2,4.84],[1,1,10]],{name:'a'});

function $f1(x) { try { return [re(coshIntegral(mul(a.Value(),x)))];} catch(e) { return Number.NaN;} }
function $f2(x) { try { return [im(coshIntegral(mul(a.Value(),x)))];} catch(e) { return Number.NaN;} }
board.create('functiongraph',[$f1, -2.0, 2.0],{strokecolor:'#5e81b5'});
board.create('functiongraph',[$f2, -2.0, 2.0],{strokecolor:'#e19c24'});


board.unsuspendUpdate();

</script>
</body>
</html>
```

**Comment by alfredwassermann** [comment] 2021-10-18 20:28
`coshIntegral(x)` seems to hang infinitely when called with `x = -1.0`.  
Further, the correct definition of `$f1` and `$f2`  is probably 

    function $f1(x) { try { return re(coshIntegral(mul(a.Value(),x)));} catch(e) { return Number.NaN;} }
    function $f2(x) { try { return im(coshIntegral(mul(a.Value(),x)));} catch(e) { return Number.NaN;} }

**Comment by paulmasson** [comment] 2021-10-18 23:30
@axkr any function that goes through the upper incomplete gamma is likely to have issues. I've spent quite a bit of time figuring out how to address problems with that function as well as `hypergeometricU`. Think I know a way forward but it will be a lot of work and I've been procrastinating. Need to get focused...

**Comment by axkr** [comment] 2021-10-19 14:53
> Further, the correct definition of `$f1` and `$f2` is probably

@alfredwassermann, @paulmasson - I inserted a JSFiddle button into the graphics `iframe`, to make it easier checking problems with the generated JavaScript.
Example:
- https://matheclipse.org/input?i=Manipulate%28Plot%28%7BRe%28Cos%28a%2Ax%29%29%2CIm%28Sin%28I%2Aa%2Ax%29%29%7D%2C%7Bx%2C-2.0%2C2.0%7D%2CPlotRange-%3E%7B-5.0%2C5.0%7D%29%2C%7Ba%2C1%2C10%7D%29

**Comment by paulmasson** [comment] 2022-04-03 23:03
@alfredwassermann you were correct that `coshIntegral` hangs at -1. Traces back to `expIntegralEi` which hangs at -1 and +i/-i. I've added a fix in d1d69f3 to avoid this and allow the page to load.

@axkr your page now finishes loading, although slowly, but nothing appears. Since this appears to be an issue with your implementation of JSXGraph, I'm closing this issue. Feel free to reopen it if there's still a problem on my end.

**Closed as completed by paulmasson** 2022-04-03 23:03 UTC

**Comment by axkr** [comment] 2022-04-18 15:09
@paulmasson should I post examples of slow Mathcell 3D renderings in a new issue or do you assume they have all the same cause?

**Comment by paulmasson** [comment] 2022-04-18 18:09
@axkr probably all the same root cause. Reopen this issue as needed. Thanks!
